HackYourFuture-CPH/Guide-IT

src/client/components/ProgressBar.components/ProgressBar.css
src/client/components/ProgressBar.components/ProgressBar.js
src/client/components/ProgressBar.components/ProgressBar.stories.js

Added a progress bar storybook component.
#9 

added progress bar stories

---

src/client/components/JobCard/JobCard.js
src/client/components/JobCard/JobCard.stories.js
src/client/components/JobCard/JobCard.styles.css
src/client/index.css

Storybook component for the result job card, it does have 2 props, title and content
Fixes #20
Run storybook with this command: npm run storybook . and you can test it by changing the value of added controls.
- [ x] I have commented my code, particularly in hard-to-understand areas

developed result job card component storybook

---

src/client/components/HomeDescription/HomeDescription.js
src/client/components/HomeDescription/HomeDescription.stories.js
src/client/components/HomeDescription/HomeDescription.styles.css

Storybook description card part of home screen
Fixes #5 
Run: npm run storybook and you will see the created component

Home description label storybook component

---

src/client/components/Modal/Modal.css
src/client/components/Modal/Modal.js
src/client/components/Modal/Modal.stories.js

Created Modal View Component ,Modal will shown up when we hover over an element that is attached with Modal.
#42 
To test it please run "npm run storybook" and hover over a small box having text "hover over here".
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] This PR is ready to be merged and not breaking any other functionality

Modal-view-component

---

src/client/components/DecriptionHome/DescriptionCareer.css
src/client/components/DecriptionHome/DescriptionCareer.js
src/client/components/DecriptionHome/DescriptionCareer.stories.js

adding home description 
Fixes #6 

description home

---

src/server/migrations/create_questions_schema.js

Created Migrations for Questions Table #28
#28 
Please run npm run db:setup then verify questions table in database .
- [x ] This PR is ready to be merged and not breaking any other functionality

Migrations-for-Questions-Table

---

.gitignore
package-lock.json
package.json

changed package.json and .gitignore to make the storybook deployment 
Fixes #39 

changed package.json and .gitignore to make the storybook deployment

---

src/server/migrations/20210427212734_answers_table.js

This PR creates the migration for the answers table.
Fixes # (#27)
run this command to test!
knex migrate:latest
- [ x] I have commented my code, particularly in hard-to-understand areas

added migration answers table

---

src/server/migrations/20210428000652_create_users_table.js

Databases: Create Migrations for Users Table issue #25

I created users table migration

---

src/server/seeds/development/02_answers.js

I have created seeding for the Answers Table
#36 
please run command: npm run knex -- seed:run

added the seeding for answers table

---

src/server/api/controllers/quiz_results.controller.js
src/server/api/routes/api-router.js
src/server/api/routes/quiz_results.router.js

Created the POST endpoint for api/quiz-results and that takes answer id and user id as parameters.
Fixes #34 
First run npm run dev. Then go to Swagger ui (http://localhost:3000/api/documentation/#/quiz_results/post_quiz_results) and post some data into quiz_results table.

POST endpoint for api/quiz-results

---

src/client/components/CardProfileResult/CardProfileResultComponent.styles.css
src/client/containers/QuizResultPage/QuizResultPage.styles.css

responsive  Quiz Result Page. I have changed CSS by adding Media Query in Quiz Result page Container and component Card Result Page(Beth's Component).
Storybook
You have to change the file name by adding .component to file names of components I  am using here. It is because we merge the Quiz result page component last week with the .component extension in file names. But Anqira PR is still not merged.
- [x ] This PR is ready to be merged and not breaking any other functionality

Responsive Quize Result Page

---

src/client/containers/404Page/404Page.container.js
src/client/containers/404Page/404Page.styles.css

Changed some CSS  style for responsiveness of the error page  and added a link to the button
#23 
First, import the error page component in the app.js and add a route for it and then test by running npm run dev

Changed some CSS for responsiveness and added link to the button

---

src/client/containers/QuizPage/QuizPage.component.js
src/client/containers/QuizPage/QuizPage.styles.css

making changes in quizPage js file for all next and back buttons working and link to the next page with rendering new images with questions and answers.. making changes in quizpage css file for responsive..

buttons work for 5 pages and make some changes in css for responsive

---

src/server/api/controllers/questions.controller.js
src/server/api/routes/api-router.js
src/server/api/routes/questions.router.js

Created the POST endpoint api/questions
#102 
npm run dev and post a question at http://localhost:3000/api/documentation/#/Questions then verify posted question in questions table in database.

POST endpoint api/questions

---

src/client/components/ResultJobFeatures/ResultJobFeatures.styles.css
src/client/containers/CareerPage/CareerPage.component.js
src/client/containers/CareerPage/CareerPage.styles.css

I made a few changes for css files for checking the responsive for career page .
please open the page  and go to developer tools and check the resolution for  1024x768 to 1920x1080

i have changed the css for career page responsiveness

---

src/server/api/routes/api-router.js

deleted one duplicate declaration of questions router.

deleted one duplicate declaration of questions router

---

src/client/containers/Home/Home.container.js
src/client/containers/Home/Home.styles.css

make sure about homepage responsiveness in different screen sizes.
Fixes # (#8 )
npm run dev

Homepage responsiveness

---

src/client/components/ProfileQuizResults/ProfileQuizResults.component.js
src/client/components/ProfileQuizResults/ProfileQuizResults.stories.js
src/client/components/ProfileQuizResults/ProfileQuizResults.styles.css

Fixes # 108
Run npm run storybook

Profile quiz results

---

src/client/containers/RegistrationPage/RegistrationPage.component.js
src/client/containers/RegistrationPage/RegistrationPage.styles.css

Responsiveness for Registration input 
Fixes # (#100)
npm run storybook

responsive for registration input

---

src/server/api/controllers/answers.controller.js

I have modify the api\controllers\answers.controller.js . Now it returns complete records from answers with given id .
Fixes # (issue) it is part of issue 
#136 
Please try to get answers by id from Swagger .  
http://localhost:5000/api/documentation/ 
- [ x] I have performed a self-review of my own code

get answer by id api/anwers modify

---

src/server/api/controllers/quiz-results.controller.js
src/server/api/routes/quiz-results.router.js

Created POST for quiz-result, insert row into quiz-results table in db.
Fixes # https://github.com/HackYourFuture-CPH/Guide-IT/issues/137
I manipulated api end points using postman to test my solution.

POST quiz result

---

src/server/api/controllers/users.controller.js
src/server/api/routes/users.router.js

I altered the users controller and router to handle the situation where an anonymous user wants quiz results
Fixes # https://github.com/HackYourFuture-CPH/Guide-IT/issues/137
I used postman to check the api endpoints to make sure the output is as expected.

Anonymous user for quiz results

---

src/client/components/ProfileQuizResults/ProfileQuizResults.component.js
src/client/components/ProfileQuizResults/ProfileQuizResults.styles.css

Improve css for profile_quiz_results

---

src/client/components/ProfileCareerResult/ProfileCareerResult.component.js
src/client/components/ProfileCareerResult/ProfileCareerResult.stories.js
src/client/components/ProfileCareerResult/ProfileCareerResult.styles.css

A component that shows the Profile Career Results 
Fixes #109 
npm run storybook on your terminal and checkout the Profile Career Result component.

Profile Career Results Component

---

src/client/components/DecriptionHome/DescriptionCareer.component.js
src/client/components/DecriptionHome/DescriptionCareer.styles.css
src/client/components/EmailRegistration/EmailForm.component.js
src/client/components/EmailRegistration/EmailForm.styles.css
src/client/components/GoogleLoginButton/GoogleLoginButton.component.js
src/client/components/GoogleLoginButton/GoogleLoginButton.styles.css
src/client/components/LeftBlueBar/LeftBlueBar.component.js
src/client/components/ProfileForm/ProfileForm.component.js
src/client/components/ProfileForm/ProfileForm.styles.css
src/client/components/ProfileQuizResults/ProfileQuizResults.component.js
src/client/components/ProfileQuizResults/ProfileQuizResults.styles.css
src/client/components/QuizAnswers/QuizAnswers.component.js
src/client/components/QuizAnswers/QuizAnswers.styles.css
src/client/components/ResultJobFeatures/ResultJobFeatures.component.js
src/client/components/SideMenu/SideMenu.component.js
src/client/components/SideMenu/SideMenu.styles.css
src/client/containers/EmptyQuizResultPage/EmptyQuizResultPage.container.js
src/client/containers/EmptyQuizResultPage/EmptyQuizResultPage.styles.css
src/client/containers/Home/Home.styles.css
src/client/containers/NextStepsPage/NextStepsPage.component.js
src/client/containers/NextStepsPage/NextStepsPage.styles.css
src/client/containers/QuizPage/QuizPage.component.js
src/client/containers/QuizPage/QuizPage.styles.css
src/client/containers/QuizResultPage/QuizResultPage.styles.css
src/client/containers/RegistrationPage/RegistrationPage.component.js
src/client/containers/RegistrationPage/RegistrationPage.styles.css

I renamed all the class names to kebab case
Fixes # 159

Renaming the Classnames according to the name conventions

---

src/server/api/routes/api-router.js

Delete modules from api-router

---

src/server/migrations/20210427152901_create_questions_table.js
src/server/migrations/20210520221859_alter_questions_table.js

I have added two more columns in questions table.
Fixes # (issue) there is no open issue for this
please run 
npm run knex -- migrate:latest
and  verify two new columns in questions table ('image_url' and 'is_agreement_question') in your database. 

added two columns in questions table

---

src/client/components/LeftBlueBar/LeftBlueBar.component.js

Link is added for (create account and login) instead of <a>.
It was done before but seems like it is overwritten.
Fixes # (#3 )
npm run storybook

Link and Router is added instead of <a> tag.

---

src/server/api/controllers/answers.controller.js
src/server/api/routes/answers.router.js

create end points for post and delete answer

---

src/client/components/Pagination/Pagination.styles.css

Added only a line in the stylesheet to center the Pagination inside Elevator

added one line to center the pagination inside Elevator component

---

src/server/seeds/development/01_questions.js

I have modify seed file for questions table by adding values for two new columns image_url and is_agreement_question.
Fixes # (issue) there is open issue for it.
If you have already pulled latest changes from develop branch and have latest migration up then please skip step 1.
step 1. Please pull latest develop branch and RUN  npm run knex -- migrate:latest from develop.
step 2. Please RUN npm run knex -- seed:run from  questions-table-seeds-change branch and verify new data in questions table.

added image_url and is_agreement_question

---

src/client/components/DecriptionHome/DescriptionCareer.component.js
src/client/containers/Home/Home.container.js

fixed home container fontSize prop type and descriptionCareer proptypes error
Fixes : No open issues for it
Run npm run dev and inspect the console, you will see the errors don't exist anymore

fixed home container fontSize and descriptionCareer proptypes error

---

src/client/components/LeftBlueBar/LeftBlueBar.component.js

Deleted unused import statement from reactRouterDom.
npm run code:lint

removed unused import from reactRouterDom

---

src/client/components/SideMenu/SideMenu.component.js

fix the route side bar menu
Fixes #171 #172

fix the route inside side menu component

---

src/client/components/LeftBlueBar/LeftBlueBar.component.js

Fixed the Router link issue in the left blue bar

Fixing the router link issue in the LeftBlueBar component

---

src/client/App.js

Added a router for capturing all the invalid routes and direct them to the Error404Page component.
Run npm run dev and check all the possible routes, especially what you have worked with, if they still are working.

added a router for capturing all the invalid routes

---

src/client/components/Buttons/Buttons.component.js
src/client/components/Buttons/Buttons.styles.css
src/client/containers/CareerPage/CareerPage.styles.css
src/client/containers/ElevatorPitchPage/ElevatorPitchPage.styles.css
src/client/containers/EmptyQuizResultPage/EmptyQuizResultPage.styles.css

Added cursor:pointer for Buttons component and deleted from other components, that are using Buttons component.

added cursor for Buttons component and deleted from others

---

src/client/components/QuizAnswers/QuizAnswers.styles.css

added cursor for the radio inputs and removed import fonts for QuizAnswers.styles

added cursor for the radio inputs and removed import fonts

---

src/client/components/Elevator/Elevator.styles.css

Fixed elevator page responsiveness
npm run dev

Fixed the responsiveness for elevator page

---

src/client/components/ProfileForm/ProfileForm.component.js
src/client/components/ProfileForm/ProfileForm.stories.js
src/client/components/ProfileForm/ProfileForm.styles.css

I have removed the input form fields in profile form component because we are not using those in guide it.
#197 
npm run storybook

i have removed the input fields in the profile component

---

src/client/components/CardProfileResult/CardProfileResult.component.js
src/client/components/JobCard/JobCard.component.js
src/client/containers/CareerPage/CareerPage.container.js

I have fixed  child key missing warnings in CareerPage and QuizResultPage container.  
Fixes # (issue) there is no open issue for it.
please run npm run dev and visit this links: http://localhost:3000/quiz-results/1 and http://localhost:3000/career/UX%20designer 
in console check for warnings.
- [ x] I have performed a self-review of my own code

fixed child key warning

---

src/client/containers/CareerPage/CareerPage.styles.css

Changed button styles in career component

changed button styles in career component

---

src/client/components/Elevator/Elevator.component.js
src/client/components/Pagination/Pagination.component.js
src/client/components/RoboModal/RoboModal.component.js

Removed dangerouslySetInnerHTML property to fix error in Elevator component.

removed dangerouslySetInnerHTML property to fix error in Elevator

---

src/client/components/RegisterTeaser/RegisterTeaser.component.js
src/client/containers/CareerPage/CareerPage.container.js
src/client/containers/QuizResultPage/QuizResultPage.container.js

I have fixed missing link to error page and login in quiz result container and  to elevator in career container. 
Fixes # (issue) there is no open issue for it.
pleae Run:  npm rund dev and go to http://localhost:3000/quiz-results/1
it will render quiz result page if you have data in quiz_results table in database for userId "1"  else it  will redirect to  error page.

fixed missing link for error,login,elevator pages

---

src/server/api/routes/api-router.js

I have removed duplicate routes from src\server\api\routes\api-router.js.
Fixes # (issue) there is  no open issue for it.
npm run dev

removed-2-duplicate-routes

---

src/client/components/DecriptionHome/DescriptionCareer.styles.css
src/client/containers/Home/Home.container.js
src/client/containers/Home/Home.styles.css

worked on responsiveness, also for mobile
Fixes # (issue) No open issue
Run npm run dev and test that hoempage is responsive

worked on home-page responsiveness

---

src/client/containers/Home/Home.styles.css

fixed burger menu styles

---

src/client/containers/ProfilePage/ProfilePage.container.js

Typo mistake in profile page.
npm run dev

i have fixed typo mistake in profile page

---

src/client/containers/QuizPage/QuizPage.container.js
src/client/containers/QuizPage/QuizPage.styles.css

I have added a prompt when no answer is selected. The NEXT button in the quiz page will not work until an answer is selected.
Fixes # no issue
Run "npm run dev" and try the quiz. Click NEXT button without selecting an answer.

Prompt when no answer is selected

---

src/client/components/ProfileQuizResults/ProfileQuizResults.styles.css
src/client/containers/ProfilePage/ProfilePage.styles.css

made changes in .css  classnames to not overlap other changes.

changed classnames

---

src/client/components/QuizAnswers/QuizAnswers.component.js

There was an error in the quiz-page due to a prop types requirement for a boolean as IsAgreementQuestion. In the database it is either 0 or 1, so in the QuizAnswers.component, I changed treatment of the prop from a boolean to a number.
Fixes # 
Open branch and run "npm run dev". Run test through and check for errors.

Changed isAgreement question from boolean to number

---

src/client/components/LeftBlueBar/LeftBlueBar.component.js
src/client/containers/ProfilePage/ProfilePage.container.js

Added My profile to home, if user is logged in, and also in profile page changed the end point, which we are using to get the user information
Fixes #225

added profile button to home page if user logged in

---

src/server/seeds/production/01_questions.js

I changed production seeding so it is the same as in development (image_url)

Change production seeding

---

src/client/containers/NextStepsPage/NextStepsPage.container.js
src/client/containers/NextStepsPage/NextStepsPage.styles.css

Fixed next step page stylings
#228 
npm run dev

Fixed next step page stylings

---

src/client/components/LeftBlueBar/LeftBlueBar.component.js
src/client/components/LeftBlueBar/LeftBlueBar.styles.css
src/client/containers/Home/Home.styles.css

Changed the button styling, added border and space to the login text in homepage

changed the button styles and added border and space to the login text

---

src/client/components/Question/Question.styles.css

fixed issue with background image shownig borders in the quiz

---

src/client/components/HomepageHeader/header.styles.css
src/client/containers/Home/Home.styles.css

added shadows for homepage header and homepage buttons

added shadows for homepage header and homepage buttons

---

package.json

Change postbuild script to avoid seeding every build. 

Change postbuild script to avoid seeding every build
